name: Publish
on:
  push:
    branches: ["main", "beta"]
  pull_request:
    branches: ["main", "beta", "next"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI
        uses: actions/checkout@v2

      #----------------------------------------------
      # Setup Node Environment
      #----------------------------------------------
      - name: Use Node 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      #----------------------------------------------
      # Cache modules
      #----------------------------------------------
      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      #----------------------------------------------
      # Install Dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      #----------------------------------------------
      # Run unit tests
      #----------------------------------------------
      - name: Test
        run: yarn test

      #--------------------------------------------
      # Pull latest changes from the current branch
      #--------------------------------------------
      - name: Pull latest changes
        run: git pull origin ${{ github.ref }}

      #--------------------------------------------------
      # Set Repository URL in package.json if not present
      #--------------------------------------------------
      - name: Set repository URL in package.json
        run: |
          REPO_URL=$(git config --get remote.origin.url)
          PACKAGE_REPO=$(jq -r '.repository' package.json)
          PACKAGE_HOMEPAGE=$(jq -r '.homepage' package.json)
          jq --arg REPO_URL "$REPO_URL" '.repository = $REPO_URL | .homepage = $REPO_URL' package.json > tmp.json && mv tmp.json package.json
          UPDATED_PACKAGE_REPO=$(jq -r '.repository' package.json)
          UPDATED_PACKAGE_HOMEPAGE=$(jq -r '.homepage' package.json)

      #-----------------------------------------------------------------------------
      # Replace placeholders with repository author id in README and issue templates
      #-----------------------------------------------------------------------------
      - name: Replace placeholders with repository author id
        run: |
          REPO_AUTHOR_ID=$(echo $(git config --get remote.origin.url) | cut -d'/' -f4)
          sed -i "s/<github-username>/$REPO_AUTHOR_ID/g" README.md
          sed -i "s/assignees:$/assignees: $REPO_AUTHOR_ID/" .github/ISSUE_TEMPLATE/bug_report.md
          sed -i "s/assignees:$/assignees: $REPO_AUTHOR_ID/" .github/ISSUE_TEMPLATE/feature_request.md

      #--------------------------------------------------------------------------
      # Commit README, package.json and issue templates changes if they exist
      #--------------------------------------------------------------------------
      - name: Commit configuration changes
        id: commit_changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json README.md .github/ISSUE_TEMPLATE/bug_report.md .github/ISSUE_TEMPLATE/feature_request.md
          GIT_DIFF=$(git diff --staged --quiet; echo $?)
          if [[ $GIT_DIFF -ne 0 ]]; then
            git commit -m "chore(config): Updated library config"
            echo "committed=true" >> "$GITHUB_OUTPUT"
          else
            echo "committed=false" >> "$GITHUB_OUTPUT"
          fi

      #-------------------------------
      # Push changes to the repository if there are any commits
      #-------------------------------
      - name: Push changes
        if: steps.commit_changes.outputs.committed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}

  # publish:
  #   if: ${{github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')}}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2

  #     #----------------------------------------------
  #     # Setup Node Environment
  #     #----------------------------------------------
  #     - name: Use NodeJs 20.x
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 20.x

  #     #----------------------------------------------
  #     # Cache modules
  #     #----------------------------------------------
  #     - name: Use cached node_modules
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: nodeModules-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           nodeModules-

  #     #----------------------------------------------
  #     # Install dependencies
  #     #----------------------------------------------
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     #----------------------------------------------
  #     # Run unit tests
  #     #----------------------------------------------
  #     - name: Test
  #       run: yarn test:cov

  #     #----------------------------------------------
  #     # Store coverage
  #     #----------------------------------------------
  #     - name: Upload coverage to Codacy
  #       uses: codacy/codacy-coverage-reporter-action@1.0.0
  #       with:
  #         # API project token to retrieve your remote Codacy configuration for the project being analyzed
  #         project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  #         # Optional comma separated list of coverage reports to send to Codacy
  #         coverage-reports: ./coverage/lcov.info

  #     #----------------------------------------------
  #     # Build dist package
  #     #----------------------------------------------
  #     - name: Build
  #       run: yarn build

  #     #----------------------------------------------
  #     # Publish package
  #     #----------------------------------------------
  #     - name: Semantic Release
  #       run: yarn semantic-release
  #       env:
  #         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  #         GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
